---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/ovirt-infra-vars.yaml
  tasks:
    - name: Template Openshift hosts files
      template:
        src: hosts.j2
        dest: "{{ playbook_dir }}/inventory/hosts"
      run_once: true

    - local_action: meta
        refresh_inventory

    - name: "Establish rhv pre-req packages"
      set_fact:
        openshift_deploy_packages_by_provider: ['python-ovirt-engine-sdk4']

    - name: "Be sure all pre-req rhv packages are installed"
      yum: name={{item}} state=installed
      with_items:
        - "{{ openshift_deploy_packages_by_provider }}"

    - name: copy dynamic inventory script to inventory dir
      copy:
        src: ovirt4.py
        dest: ./inventory/ovirt4.py

    - name: download ca.pem from RHV Manager
      get_url:
        url: 'http://{{ engine_hostname }}/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA'
        dest: "{{ playbook_dir }}/files/ca.pem"
        force: yes
      register: ca_file
      tags:
        - ca

    - name: template dynamic inventory  ini (ovirt.init)
      template:
        src: ovirt.ini.j2
        dest: "./inventory/ovirt.ini"
      tags:
        - ca

- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/ovirt-infra-vars.yaml

  pre_tasks:
    - name: Log in to oVirt
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always
  
  roles:
    - ovirt-image-template
    - ovirt-vm-infra

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

    #JTH: Fix for below
    - local_action: meta 
        refresh_inventory

